#!/usr/bin/env bash
# start.sh — remet la stack WendigoGame à zéro (Docker + Pulumi + OIDC)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA="$ROOT/infrastructure"
SDK="$INFRA/sdks/authentik"
COMPOSE_FILE="$ROOT/docker-compose.yml"
OBSERVABILITY="${OBSERVABILITY:-1}"
MAX_WAIT="${MAX_WAIT:-360}"
PULUMI_STATE_DIR="${PULUMI_STATE_DIR:-$HOME/.pulumi-wendigo}"
export PULUMI_BACKEND_URL="file://${PULUMI_STATE_DIR}"

# Reset one-shot : vide l'état Pulumi local + purge Authentik Wendigo avant un pulumi up propre.
# Activé via WENDIGO_CLEAN_DEPLOY=1 ou ./start.sh --clean
WENDIGO_CLEAN_DEPLOY="${WENDIGO_CLEAN_DEPLOY:-0}"
for arg in "$@"; do
  [[ "$arg" == "--clean" ]] && WENDIGO_CLEAN_DEPLOY=1
done

# Binaires locaux (tsc, etc.) — postinstall.js du SDK Authentik appelle `tsc` via /bin/sh.
export PATH="$INFRA/node_modules/.bin:$SDK/node_modules/.bin:$ROOT/node_modules/.bin:${PATH:-}"

# BuildKit optionnel (runner gaston : docker classique sans buildx).
export DOCKER_BUILDKIT="${DOCKER_BUILDKIT:-0}"
export COMPOSE_DOCKER_CLI_BUILD="${COMPOSE_DOCKER_CLI_BUILD:-0}"

log()  { printf '\n▶ %s\n' "$*"; }
warn() { printf '⚠ %s\n' "$*" >&2; }
die()  { printf '✖ %s\n' "$*" >&2; exit 1; }

if command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose -f "$COMPOSE_FILE")
else
  DC=(docker compose -f "$COMPOSE_FILE")
  warn "docker-compose introuvable — fallback sur 'docker compose'"
fi

normalize_vite_oidc_url() {
  local url="${1:-http://localhost:9000/application/o/wendigo}"
  printf '%s' "${url%/}/"
}

export_vite_build_env() {
  if [[ -f "$ROOT/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "$ROOT/.env"
    set +a
  fi
  [[ -n "${VITE_API_URL:-}" ]] || export VITE_API_URL="http://localhost:8080"
  [[ -n "${VITE_AUTHENTIK_CLIENT_ID:-}" ]] || export VITE_AUTHENTIK_CLIENT_ID="wendigo-dev"
  export VITE_AUTHENTIK_URL="$(normalize_vite_oidc_url "${VITE_AUTHENTIK_URL:-}")"
}

authentik_url() {
  if [[ -n "${AUTHENTIK_URL:-}" ]]; then
    printf '%s' "${AUTHENTIK_URL%/}"
    return 0
  fi
  local url
  url="$(cd "$INFRA" && pulumi config get authentik:url 2>/dev/null || echo 'http://localhost:9000')"
  printf '%s' "${url%/}"
}

authentik_api_token() {
  if [[ -n "${AUTHENTIK_TOKEN:-}" ]]; then
    printf '%s' "$AUTHENTIK_TOKEN"
    return 0
  fi
  cd "$INFRA" && pulumi config get authentik:token 2>/dev/null || true
}

kill_stale_authentik_providers() {
  if pgrep -f 'terraform-provider-authentik' >/dev/null 2>&1; then
    warn "Arrêt des terraform-provider-authentik orphelins..."
    pkill -f 'terraform-provider-authentik' 2>/dev/null || true
    sleep 2
  fi
}

compose_up() {
  local profile_args=()
  [[ "$OBSERVABILITY" == "1" ]] && profile_args=(--profile observability)
  export_vite_build_env
  log "Docker: build + up ${profile_args[*]:-(sans observability)}"
  "${DC[@]}" "${profile_args[@]}" up -d --build
  # Backend démarré trop tôt → JWKS 404 tant que Pulumi n'a pas provisionné l'OIDC.
  "${DC[@]}" stop backend 2>/dev/null || true
}

wait_authentik() {
  local url="http://localhost:9000/-/health/ready/"
  log "Attente Authentik ($url) — peut prendre ~5 min..."
  local i=0
  while (( i < MAX_WAIT )); do
    local code
    code="$(curl -s -o /dev/null -w '%{http_code}' "$url" 2>/dev/null || echo 000)"
    if [[ "$code" == "200" ]]; then
      log "Authentik prêt (HTTP 200) après ${i}s"
      return 0
    fi
    if (( i % 30 == 0 )); then
      printf '  … %ds (dernier code: %s)\n' "$i" "$code"
    fi
    sleep 1
    i=$((i + 1))
  done
  die "Authentik pas prêt après ${MAX_WAIT}s"
}

patch_authentik_sdk_sources() {
  [[ -d "$SDK" ]] || return 0

  sed -i '/import \* as utilities from "\.\/utilities";/d' "$SDK/config/vars.ts" 2>/dev/null || true
  sed -i '/import \* as utilities from "\.\/utilities";/d' "$SDK/types/index.ts" 2>/dev/null || true
  if grep -q 'from "\.\/types\/input"' "$SDK/types/input.ts" 2>/dev/null; then
    cat > "$SDK/types/input.ts" <<'EOF'
// *** WARNING: this file was generated by pulumi-language-nodejs. ***

export {};
EOF
  fi
  sed -i '/import \* as inputs from "\.\/types\/input";/d' "$SDK/types/output.ts" 2>/dev/null || true
  sed -i '/import \* as outputs from "\.\/types\/output";/d' "$SDK/types/output.ts" 2>/dev/null || true
  sed -i 's/outputs\.GetGroupsGroupUsersObj/GetGroupsGroupUsersObj/g' "$SDK/types/output.ts" 2>/dev/null || true
}

build_authentik_sdk() {
  [[ -d "$SDK" ]] || return 0
  log "Build SDK Authentik (tsc + bin/package.json)..."
  (
    cd "$SDK"
    if [[ ! -d node_modules ]]; then
      npm install --ignore-scripts
    fi
    export PATH="$SDK/node_modules/.bin:$INFRA/node_modules/.bin:${PATH:-}"
    command -v tsc >/dev/null || die "tsc introuvable (installe typescript dans $SDK ou flake.nix)"
    node scripts/postinstall.js
  )
  [[ -f "$SDK/bin/package.json" ]] || die "SDK Authentik: bin/package.json manquant après build"
}

sync_authentik_sdk_bin() {
  [[ -d "$SDK/bin" ]] || return 0
  local dest
  dest="$(find "$INFRA/node_modules" -path '*/@pulumi/authentik/bin' -type d 2>/dev/null | head -1 || true)"
  if [[ -n "$dest" && "$dest" != "$SDK/bin" ]]; then
    log "Sync bin/ SDK → node_modules pnpm..."
    mkdir -p "$dest"
    cp -a "$SDK/bin/." "$dest/"
  fi
  [[ -f "${dest:-$SDK/bin}/package.json" ]] || die "SDK Authentik introuvable dans node_modules"
}

patch_authentik_sdk() {
  patch_authentik_sdk_sources
  build_authentik_sdk
}

ensure_pulumi_deps() {
  log "Dépendances infrastructure..."
  cd "$INFRA"

  if ! grep -q '@pulumi/authentik' package.json 2>/dev/null; then
    if [[ ! -d "$SDK" ]]; then
      log "Génération SDK: pulumi package add..."
      pulumi package add terraform-provider goauthentik/authentik 2025.12.1 || true
    fi
    patch_authentik_sdk_sources
    pnpm add "@pulumi/authentik@file:sdks/authentik" || true
  fi

  patch_authentik_sdk_sources
  build_authentik_sdk
  pnpm install --ignore-scripts
  sync_authentik_sdk_bin

  if ! grep -q '"sdks"' tsconfig.json; then
    sed -i 's/"exclude": \["node_modules", "bin"\]/"exclude": ["node_modules", "bin", "sdks"]/' tsconfig.json
  fi
}

refresh_authentik_token() {
  log "Token API Authentik..."
  local token url
  url="$(authentik_url)"

  token="$("${DC[@]}" exec -T authentik-worker ak shell -c "
from authentik.core.models import Token, TokenIntents, User
admin = User.objects.get(username='akadmin')
Token.objects.filter(identifier='pulumi-deploy').delete()
t = Token.objects.create(
    user=admin,
    identifier='pulumi-deploy',
    intent=TokenIntents.INTENT_API,
)
print('TOKEN:', t.key)
" 2>/dev/null | grep '^TOKEN:' | cut -d' ' -f2)"

  [[ -n "$token" ]] || die "Impossible de récupérer le token Authentik"
  export AUTHENTIK_TOKEN="$token"
  export AUTHENTIK_URL="$url"
  (
    cd "$INFRA"
    pulumi config set --secret authentik:token "$token" 2>/dev/null || true
  )
  log "Token Authentik enregistré"
}

prune_authentik_wendigo_ak() {
  local prune_script="$INFRA/scripts/prune-wendigo-authentik-ak.py"
  [[ -f "$prune_script" ]] || return 0

  log "Purge Authentik Wendigo (ak shell / ORM)..."
  local prune_out
  "${DC[@]}" exec -T authentik-worker sh -c 'cat > /tmp/prune-wendigo-ak.py' < "$prune_script"
  prune_out="$("${DC[@]}" exec -T authentik-worker ak shell -c "exec(open('/tmp/prune-wendigo-ak.py').read())" 2>&1 | grep -E '\{"pruned"' | tail -1 || true)"
  if [[ -n "$prune_out" ]]; then
    log "  $prune_out"
  else
    warn "Purge Authentik via ak shell sans résultat — complément REST..."
  fi
}

prune_authentik_wendigo_rest() {
  local token url attempt
  token="$(authentik_api_token)"
  url="$(authentik_url)"
  [[ -n "$token" ]] || { warn "Token Authentik absent — purge REST ignorée"; return 0; }

  log "Purge Authentik Wendigo (API REST)..."
  for attempt in 1 2 3 4 5; do
    wait_authentik
    if python3 "$INFRA/scripts/prune-wendigo-authentik.py" --url "$url" --token "$token"; then
      return 0
    fi
    warn "Purge REST tentative $attempt/5 échouée — attente Authentik..."
    sleep 15
  done
  return 1
}

purge_authentik_wendigo() {
  wait_authentik
  prune_authentik_wendigo_ak
  prune_authentik_wendigo_rest || die "Purge Authentik Wendigo incomplète — impossible de faire un clean deploy"
}

reset_pulumi_state() {
  log "Reset état Pulumi ($PULUMI_STATE_DIR)..."
  kill_stale_authentik_providers
  if [[ -d "$PULUMI_STATE_DIR" ]]; then
    rm -rf "$PULUMI_STATE_DIR"
  fi
  mkdir -p "$PULUMI_STATE_DIR"
}

ensure_pulumi_stack() {
  cd "$INFRA"
  pulumi stack select dev 2>/dev/null || pulumi stack init dev --non-interactive
}

run_pulumi() {
  log "Pulumi up (état: $PULUMI_STATE_DIR)..."
  export PULUMI_CONFIG_PASSPHRASE="${PULUMI_CONFIG_PASSPHRASE:-}"
  mkdir -p "$PULUMI_STATE_DIR"
  kill_stale_authentik_providers

  if [[ "$WENDIGO_CLEAN_DEPLOY" == "1" ]]; then
    log "Mode clean deploy — reset état + purge Authentik Wendigo"
    refresh_authentik_token
    reset_pulumi_state
    purge_authentik_wendigo
    refresh_authentik_token
    ensure_pulumi_stack
  else
    wait_authentik
    refresh_authentik_token
    ensure_pulumi_stack
  fi

  cd "$INFRA"
  wait_authentik
  log "pulumi up (provisionnement complet)..."
  pulumi up -y --parallel 1

  log "Redémarrage backend (JWKS OIDC après pulumi up)..."
  "${DC[@]}" up -d --force-recreate backend frontend
}

rebuild_frontend() {
  log "Rebuild frontend (OIDC vars)..."
  export_vite_build_env
  log "  VITE_AUTHENTIK_URL=$VITE_AUTHENTIK_URL"
  log "  VITE_AUTHENTIK_CLIENT_ID=$VITE_AUTHENTIK_CLIENT_ID"
  "${DC[@]}" build \
    --build-arg "VITE_API_URL=${VITE_API_URL}" \
    --build-arg "VITE_AUTHENTIK_URL=${VITE_AUTHENTIK_URL}" \
    --build-arg "VITE_AUTHENTIK_CLIENT_ID=${VITE_AUTHENTIK_CLIENT_ID}" \
    frontend
  "${DC[@]}" up -d --force-recreate backend frontend
}

verify() {
  log "Vérifications finales..."
  curl -sf "http://localhost:9000/application/o/wendigo/.well-known/openid-configuration" | head -c 80 && echo || \
    warn "OIDC discovery pas encore dispo"
  local jwks
  jwks="$(curl -sf "http://localhost:9000/application/o/wendigo/jwks/" 2>/dev/null || echo '{}')"
  if [[ "$jwks" == "{}" || "$jwks" == '{"keys":[]}' ]]; then
    warn "JWKS vide — le provider OIDC doit utiliser une signing_key RSA (pulumi up)"
  else
    log "JWKS OIDC OK (clés publiques présentes)"
  fi
  curl -sf -o /dev/null "http://localhost:5173/" && log "Frontend OK : http://localhost:5173" || warn "Frontend pas encore up"
  local i=0
  while (( i < 30 )); do
    if curl -sf -o /dev/null "http://localhost:8080/metrics"; then
      log "Backend OK : http://localhost:8080"
      return 0
    fi
    sleep 1
    i=$((i + 1))
  done
  warn "Backend pas encore up — logs: ${DC[*]} logs backend"
}

# ─── Main ───────────────────────────────────────────────────────────────────
cd "$ROOT"
command -v nix >/dev/null || die "Nix requis (nix develop)"
command -v docker >/dev/null || die "Docker requis"

compose_up
wait_authentik
ensure_pulumi_deps
run_pulumi
rebuild_frontend
verify

log "Terminé — http://localhost:5173 (login OIDC)"
log "Admin Authentik : akadmin / ton-mot-de-passe-bootstrap-secr3t"
[[ "$OBSERVABILITY" == "1" ]] && log "Grafana : http://localhost:3000 (admin/admin)"
