// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Agent extends pulumi.CustomResource {
    /**
     * Get an existing Agent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AgentState, opts?: pulumi.CustomResourceOptions): Agent {
        return new Agent(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/agent:Agent';

    /**
     * Returns true if the given object is an instance of Agent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Agent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Agent.__pulumiType;
    }

    declare public readonly agentId: pulumi.Output<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    declare public readonly attributes: pulumi.Output<string | undefined>;
    declare public readonly email: pulumi.Output<string | undefined>;
    declare public readonly expires: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly expiring: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly isActive: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to ``.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * PK of the user that owns this agent. If not set, a new parent user is created automatically. Generated.
     */
    declare public readonly parent: pulumi.Output<number>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`mirror`" pulumi-lang-dotnet="`Mirror`" pulumi-lang-go="`mirror`" pulumi-lang-python="`mirror`" pulumi-lang-yaml="`mirror`" pulumi-lang-java="`mirror`" pulumi-lang-hcl="`mirror`">`mirror`</span>
     *   - <span pulumi-lang-nodejs="`copy`" pulumi-lang-dotnet="`Copy`" pulumi-lang-go="`copy`" pulumi-lang-python="`copy`" pulumi-lang-yaml="`copy`" pulumi-lang-java="`copy`" pulumi-lang-hcl="`copy`">`copy`</span>
     *   - <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>
     *      Mirroring/copying requires an explicit <span pulumi-lang-nodejs="`parent`" pulumi-lang-dotnet="`Parent`" pulumi-lang-go="`parent`" pulumi-lang-python="`parent`" pulumi-lang-yaml="`parent`" pulumi-lang-java="`parent`" pulumi-lang-hcl="`parent`">`parent`</span>; without one the server falls back to <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Generated.
     */
    declare public readonly policyBehavior: pulumi.Output<string>;
    /**
     * The agent's API token. Only returned once, at creation. Generated.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * Identifier of the agent's API token, so its key can be retrieved/copied later. Generated.
     */
    declare public /*out*/ readonly tokenIdentifier: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public /*out*/ readonly uid: pulumi.Output<string>;
    declare public readonly username: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Agent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AgentArgs | AgentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AgentState | undefined;
            resourceInputs["agentId"] = state?.agentId;
            resourceInputs["attributes"] = state?.attributes;
            resourceInputs["email"] = state?.email;
            resourceInputs["expires"] = state?.expires;
            resourceInputs["expiring"] = state?.expiring;
            resourceInputs["isActive"] = state?.isActive;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["policyBehavior"] = state?.policyBehavior;
            resourceInputs["token"] = state?.token;
            resourceInputs["tokenIdentifier"] = state?.tokenIdentifier;
            resourceInputs["uid"] = state?.uid;
            resourceInputs["username"] = state?.username;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as AgentArgs | undefined;
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["agentId"] = args?.agentId;
            resourceInputs["attributes"] = args?.attributes;
            resourceInputs["email"] = args?.email;
            resourceInputs["expires"] = args?.expires;
            resourceInputs["expiring"] = args?.expiring;
            resourceInputs["isActive"] = args?.isActive;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["policyBehavior"] = args?.policyBehavior;
            resourceInputs["username"] = args?.username;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenIdentifier"] = undefined /*out*/;
            resourceInputs["uid"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Agent.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Agent resources.
 */
export interface AgentState {
    agentId?: pulumi.Input<string | undefined>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    attributes?: pulumi.Input<string | undefined>;
    email?: pulumi.Input<string | undefined>;
    expires?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    expiring?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    isActive?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to ``.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * PK of the user that owns this agent. If not set, a new parent user is created automatically. Generated.
     */
    parent?: pulumi.Input<number | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`mirror`" pulumi-lang-dotnet="`Mirror`" pulumi-lang-go="`mirror`" pulumi-lang-python="`mirror`" pulumi-lang-yaml="`mirror`" pulumi-lang-java="`mirror`" pulumi-lang-hcl="`mirror`">`mirror`</span>
     *   - <span pulumi-lang-nodejs="`copy`" pulumi-lang-dotnet="`Copy`" pulumi-lang-go="`copy`" pulumi-lang-python="`copy`" pulumi-lang-yaml="`copy`" pulumi-lang-java="`copy`" pulumi-lang-hcl="`copy`">`copy`</span>
     *   - <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>
     *      Mirroring/copying requires an explicit <span pulumi-lang-nodejs="`parent`" pulumi-lang-dotnet="`Parent`" pulumi-lang-go="`parent`" pulumi-lang-python="`parent`" pulumi-lang-yaml="`parent`" pulumi-lang-java="`parent`" pulumi-lang-hcl="`parent`">`parent`</span>; without one the server falls back to <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Generated.
     */
    policyBehavior?: pulumi.Input<string | undefined>;
    /**
     * The agent's API token. Only returned once, at creation. Generated.
     */
    token?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the agent's API token, so its key can be retrieved/copied later. Generated.
     */
    tokenIdentifier?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    uid?: pulumi.Input<string | undefined>;
    username?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    uuid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Agent resource.
 */
export interface AgentArgs {
    agentId?: pulumi.Input<string | undefined>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    attributes?: pulumi.Input<string | undefined>;
    email?: pulumi.Input<string | undefined>;
    expires?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    expiring?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    isActive?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to ``.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * PK of the user that owns this agent. If not set, a new parent user is created automatically. Generated.
     */
    parent?: pulumi.Input<number | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`mirror`" pulumi-lang-dotnet="`Mirror`" pulumi-lang-go="`mirror`" pulumi-lang-python="`mirror`" pulumi-lang-yaml="`mirror`" pulumi-lang-java="`mirror`" pulumi-lang-hcl="`mirror`">`mirror`</span>
     *   - <span pulumi-lang-nodejs="`copy`" pulumi-lang-dotnet="`Copy`" pulumi-lang-go="`copy`" pulumi-lang-python="`copy`" pulumi-lang-yaml="`copy`" pulumi-lang-java="`copy`" pulumi-lang-hcl="`copy`">`copy`</span>
     *   - <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>
     *      Mirroring/copying requires an explicit <span pulumi-lang-nodejs="`parent`" pulumi-lang-dotnet="`Parent`" pulumi-lang-go="`parent`" pulumi-lang-python="`parent`" pulumi-lang-yaml="`parent`" pulumi-lang-java="`parent`" pulumi-lang-hcl="`parent`">`parent`</span>; without one the server falls back to <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Generated.
     */
    policyBehavior?: pulumi.Input<string | undefined>;
    username: pulumi.Input<string>;
}
