// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ObjectAttribute extends pulumi.CustomResource {
    /**
     * Get an existing ObjectAttribute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ObjectAttributeState, opts?: pulumi.CustomResourceOptions): ObjectAttribute {
        return new ObjectAttribute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/objectAttribute:ObjectAttribute';

    /**
     * Returns true if the given object is an instance of ObjectAttribute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ObjectAttribute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ObjectAttribute.__pulumiType;
    }

    /**
     * Generated.
     */
    declare public /*out*/ readonly created: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly group: pulumi.Output<string | undefined>;
    declare public readonly isRequired: pulumi.Output<boolean | undefined>;
    declare public readonly isUnique: pulumi.Output<boolean | undefined>;
    declare public readonly key: pulumi.Output<string>;
    declare public readonly label: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string>;
    /**
     * Objects that are managed by authentik are created/updated automatically and may be overwritten by later migrations.
     */
    declare public readonly managed: pulumi.Output<string | undefined>;
    declare public readonly objectAttributeId: pulumi.Output<string>;
    /**
     * Content-type of the objects this attribute definition applies to, e.g. `authentik_core.user`.
     */
    declare public readonly objectType: pulumi.Output<string>;
    declare public readonly regex: pulumi.Output<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`" pulumi-lang-hcl="`text`">`text`</span>
     *   - <span pulumi-lang-nodejs="`number`" pulumi-lang-dotnet="`Number`" pulumi-lang-go="`number`" pulumi-lang-python="`number`" pulumi-lang-yaml="`number`" pulumi-lang-java="`number`" pulumi-lang-hcl="`number`">`number`</span>
     *   - <span pulumi-lang-nodejs="`boolean`" pulumi-lang-dotnet="`Boolean`" pulumi-lang-go="`boolean`" pulumi-lang-python="`boolean`" pulumi-lang-yaml="`boolean`" pulumi-lang-java="`boolean`" pulumi-lang-hcl="`boolean`">`boolean`</span>
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a ObjectAttribute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ObjectAttributeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ObjectAttributeArgs | ObjectAttributeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ObjectAttributeState | undefined;
            resourceInputs["created"] = state?.created;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["group"] = state?.group;
            resourceInputs["isRequired"] = state?.isRequired;
            resourceInputs["isUnique"] = state?.isUnique;
            resourceInputs["key"] = state?.key;
            resourceInputs["label"] = state?.label;
            resourceInputs["lastUpdated"] = state?.lastUpdated;
            resourceInputs["managed"] = state?.managed;
            resourceInputs["objectAttributeId"] = state?.objectAttributeId;
            resourceInputs["objectType"] = state?.objectType;
            resourceInputs["regex"] = state?.regex;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as ObjectAttributeArgs | undefined;
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.label === undefined && !opts.urn) {
                throw new Error("Missing required property 'label'");
            }
            if (args?.objectType === undefined && !opts.urn) {
                throw new Error("Missing required property 'objectType'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["group"] = args?.group;
            resourceInputs["isRequired"] = args?.isRequired;
            resourceInputs["isUnique"] = args?.isUnique;
            resourceInputs["key"] = args?.key;
            resourceInputs["label"] = args?.label;
            resourceInputs["managed"] = args?.managed;
            resourceInputs["objectAttributeId"] = args?.objectAttributeId;
            resourceInputs["objectType"] = args?.objectType;
            resourceInputs["regex"] = args?.regex;
            resourceInputs["type"] = args?.type;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ObjectAttribute.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ObjectAttribute resources.
 */
export interface ObjectAttributeState {
    /**
     * Generated.
     */
    created?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    group?: pulumi.Input<string | undefined>;
    isRequired?: pulumi.Input<boolean | undefined>;
    isUnique?: pulumi.Input<boolean | undefined>;
    key?: pulumi.Input<string | undefined>;
    label?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    lastUpdated?: pulumi.Input<string | undefined>;
    /**
     * Objects that are managed by authentik are created/updated automatically and may be overwritten by later migrations.
     */
    managed?: pulumi.Input<string | undefined>;
    objectAttributeId?: pulumi.Input<string | undefined>;
    /**
     * Content-type of the objects this attribute definition applies to, e.g. `authentik_core.user`.
     */
    objectType?: pulumi.Input<string | undefined>;
    regex?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`" pulumi-lang-hcl="`text`">`text`</span>
     *   - <span pulumi-lang-nodejs="`number`" pulumi-lang-dotnet="`Number`" pulumi-lang-go="`number`" pulumi-lang-python="`number`" pulumi-lang-yaml="`number`" pulumi-lang-java="`number`" pulumi-lang-hcl="`number`">`number`</span>
     *   - <span pulumi-lang-nodejs="`boolean`" pulumi-lang-dotnet="`Boolean`" pulumi-lang-go="`boolean`" pulumi-lang-python="`boolean`" pulumi-lang-yaml="`boolean`" pulumi-lang-java="`boolean`" pulumi-lang-hcl="`boolean`">`boolean`</span>
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ObjectAttribute resource.
 */
export interface ObjectAttributeArgs {
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    group?: pulumi.Input<string | undefined>;
    isRequired?: pulumi.Input<boolean | undefined>;
    isUnique?: pulumi.Input<boolean | undefined>;
    key: pulumi.Input<string>;
    label: pulumi.Input<string>;
    /**
     * Objects that are managed by authentik are created/updated automatically and may be overwritten by later migrations.
     */
    managed?: pulumi.Input<string | undefined>;
    objectAttributeId?: pulumi.Input<string | undefined>;
    /**
     * Content-type of the objects this attribute definition applies to, e.g. `authentik_core.user`.
     */
    objectType: pulumi.Input<string>;
    regex?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`" pulumi-lang-hcl="`text`">`text`</span>
     *   - <span pulumi-lang-nodejs="`number`" pulumi-lang-dotnet="`Number`" pulumi-lang-go="`number`" pulumi-lang-python="`number`" pulumi-lang-yaml="`number`" pulumi-lang-java="`number`" pulumi-lang-hcl="`number`">`number`</span>
     *   - <span pulumi-lang-nodejs="`boolean`" pulumi-lang-dotnet="`Boolean`" pulumi-lang-go="`boolean`" pulumi-lang-python="`boolean`" pulumi-lang-yaml="`boolean`" pulumi-lang-java="`boolean`" pulumi-lang-hcl="`boolean`">`boolean`</span>
     */
    type: pulumi.Input<string>;
}
