// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RequestRuleChildBinding extends pulumi.CustomResource {
    /**
     * Get an existing RequestRuleChildBinding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RequestRuleChildBindingState, opts?: pulumi.CustomResourceOptions): RequestRuleChildBinding {
        return new RequestRuleChildBinding(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/requestRuleChildBinding:RequestRuleChildBinding';

    /**
     * Returns true if the given object is an instance of RequestRuleChildBinding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RequestRuleChildBinding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RequestRuleChildBinding.__pulumiType;
    }

    /**
     * UUID of the<span pulumi-lang-nodejs=" authentik.RequestRuleBinding " pulumi-lang-dotnet=" authentik.RequestRuleBinding " pulumi-lang-go=" RequestRuleBinding " pulumi-lang-python=" RequestRuleBinding " pulumi-lang-yaml=" authentik.RequestRuleBinding " pulumi-lang-java=" authentik.RequestRuleBinding " pulumi-lang-hcl=" authentik_request_rule_binding "> authentik.RequestRuleBinding </span>this child binding extends.
     */
    declare public readonly binding: pulumi.Output<string>;
    declare public readonly requestRuleChildBindingId: pulumi.Output<string>;
    /**
     * ID of the additional object this child binding makes requestable alongside the parent binding's target.
     */
    declare public readonly target: pulumi.Output<string>;

    /**
     * Create a RequestRuleChildBinding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RequestRuleChildBindingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RequestRuleChildBindingArgs | RequestRuleChildBindingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RequestRuleChildBindingState | undefined;
            resourceInputs["binding"] = state?.binding;
            resourceInputs["requestRuleChildBindingId"] = state?.requestRuleChildBindingId;
            resourceInputs["target"] = state?.target;
        } else {
            const args = argsOrState as RequestRuleChildBindingArgs | undefined;
            if (args?.binding === undefined && !opts.urn) {
                throw new Error("Missing required property 'binding'");
            }
            if (args?.target === undefined && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            resourceInputs["binding"] = args?.binding;
            resourceInputs["requestRuleChildBindingId"] = args?.requestRuleChildBindingId;
            resourceInputs["target"] = args?.target;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RequestRuleChildBinding.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RequestRuleChildBinding resources.
 */
export interface RequestRuleChildBindingState {
    /**
     * UUID of the<span pulumi-lang-nodejs=" authentik.RequestRuleBinding " pulumi-lang-dotnet=" authentik.RequestRuleBinding " pulumi-lang-go=" RequestRuleBinding " pulumi-lang-python=" RequestRuleBinding " pulumi-lang-yaml=" authentik.RequestRuleBinding " pulumi-lang-java=" authentik.RequestRuleBinding " pulumi-lang-hcl=" authentik_request_rule_binding "> authentik.RequestRuleBinding </span>this child binding extends.
     */
    binding?: pulumi.Input<string | undefined>;
    requestRuleChildBindingId?: pulumi.Input<string | undefined>;
    /**
     * ID of the additional object this child binding makes requestable alongside the parent binding's target.
     */
    target?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a RequestRuleChildBinding resource.
 */
export interface RequestRuleChildBindingArgs {
    /**
     * UUID of the<span pulumi-lang-nodejs=" authentik.RequestRuleBinding " pulumi-lang-dotnet=" authentik.RequestRuleBinding " pulumi-lang-go=" RequestRuleBinding " pulumi-lang-python=" RequestRuleBinding " pulumi-lang-yaml=" authentik.RequestRuleBinding " pulumi-lang-java=" authentik.RequestRuleBinding " pulumi-lang-hcl=" authentik_request_rule_binding "> authentik.RequestRuleBinding </span>this child binding extends.
     */
    binding: pulumi.Input<string>;
    requestRuleChildBindingId?: pulumi.Input<string | undefined>;
    /**
     * ID of the additional object this child binding makes requestable alongside the parent binding's target.
     */
    target: pulumi.Input<string>;
}
