// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RequestRuleBinding extends pulumi.CustomResource {
    /**
     * Get an existing RequestRuleBinding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RequestRuleBindingState, opts?: pulumi.CustomResourceOptions): RequestRuleBinding {
        return new RequestRuleBinding(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/requestRuleBinding:RequestRuleBinding';

    /**
     * Returns true if the given object is an instance of RequestRuleBinding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RequestRuleBinding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RequestRuleBinding.__pulumiType;
    }

    /**
     * The maximum duration a grant approved against this binding can last. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    declare public readonly expiryGrantedMax: pulumi.Output<string>;
    /**
     * How long a request against this binding stays pending before it automatically lapses if not approved or denied. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    declare public readonly expiryPending: pulumi.Output<string>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`any`" pulumi-lang-dotnet="`Any`" pulumi-lang-go="`any`" pulumi-lang-python="`any`" pulumi-lang-yaml="`any`" pulumi-lang-java="`any`" pulumi-lang-hcl="`any`">`any`</span>
     *      Generated.
     */
    declare public readonly policyEngineMode: pulumi.Output<string>;
    /**
     * Objects related to this binding's target, derived server-side. Generated.
     */
    declare public /*out*/ readonly relateds: pulumi.Output<string[]>;
    declare public readonly requestRuleBindingId: pulumi.Output<string>;
    /**
     * UUID of the<span pulumi-lang-nodejs=" authentik.RequestRule " pulumi-lang-dotnet=" authentik.RequestRule " pulumi-lang-go=" RequestRule " pulumi-lang-python=" RequestRule " pulumi-lang-yaml=" authentik.RequestRule " pulumi-lang-java=" authentik.RequestRule " pulumi-lang-hcl=" authentik_request_rule "> authentik.RequestRule </span>this binding applies.
     */
    declare public readonly rule: pulumi.Output<string>;
    /**
     * ID of the object this binding makes requestable.
     */
    declare public readonly target: pulumi.Output<string>;

    /**
     * Create a RequestRuleBinding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RequestRuleBindingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RequestRuleBindingArgs | RequestRuleBindingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RequestRuleBindingState | undefined;
            resourceInputs["expiryGrantedMax"] = state?.expiryGrantedMax;
            resourceInputs["expiryPending"] = state?.expiryPending;
            resourceInputs["policyEngineMode"] = state?.policyEngineMode;
            resourceInputs["relateds"] = state?.relateds;
            resourceInputs["requestRuleBindingId"] = state?.requestRuleBindingId;
            resourceInputs["rule"] = state?.rule;
            resourceInputs["target"] = state?.target;
        } else {
            const args = argsOrState as RequestRuleBindingArgs | undefined;
            if (args?.rule === undefined && !opts.urn) {
                throw new Error("Missing required property 'rule'");
            }
            if (args?.target === undefined && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            resourceInputs["expiryGrantedMax"] = args?.expiryGrantedMax;
            resourceInputs["expiryPending"] = args?.expiryPending;
            resourceInputs["policyEngineMode"] = args?.policyEngineMode;
            resourceInputs["requestRuleBindingId"] = args?.requestRuleBindingId;
            resourceInputs["rule"] = args?.rule;
            resourceInputs["target"] = args?.target;
            resourceInputs["relateds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RequestRuleBinding.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RequestRuleBinding resources.
 */
export interface RequestRuleBindingState {
    /**
     * The maximum duration a grant approved against this binding can last. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    expiryGrantedMax?: pulumi.Input<string | undefined>;
    /**
     * How long a request against this binding stays pending before it automatically lapses if not approved or denied. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    expiryPending?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`any`" pulumi-lang-dotnet="`Any`" pulumi-lang-go="`any`" pulumi-lang-python="`any`" pulumi-lang-yaml="`any`" pulumi-lang-java="`any`" pulumi-lang-hcl="`any`">`any`</span>
     *      Generated.
     */
    policyEngineMode?: pulumi.Input<string | undefined>;
    /**
     * Objects related to this binding's target, derived server-side. Generated.
     */
    relateds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    requestRuleBindingId?: pulumi.Input<string | undefined>;
    /**
     * UUID of the<span pulumi-lang-nodejs=" authentik.RequestRule " pulumi-lang-dotnet=" authentik.RequestRule " pulumi-lang-go=" RequestRule " pulumi-lang-python=" RequestRule " pulumi-lang-yaml=" authentik.RequestRule " pulumi-lang-java=" authentik.RequestRule " pulumi-lang-hcl=" authentik_request_rule "> authentik.RequestRule </span>this binding applies.
     */
    rule?: pulumi.Input<string | undefined>;
    /**
     * ID of the object this binding makes requestable.
     */
    target?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a RequestRuleBinding resource.
 */
export interface RequestRuleBindingArgs {
    /**
     * The maximum duration a grant approved against this binding can last. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    expiryGrantedMax?: pulumi.Input<string | undefined>;
    /**
     * How long a request against this binding stays pending before it automatically lapses if not approved or denied. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    expiryPending?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`any`" pulumi-lang-dotnet="`Any`" pulumi-lang-go="`any`" pulumi-lang-python="`any`" pulumi-lang-yaml="`any`" pulumi-lang-java="`any`" pulumi-lang-hcl="`any`">`any`</span>
     *      Generated.
     */
    policyEngineMode?: pulumi.Input<string | undefined>;
    requestRuleBindingId?: pulumi.Input<string | undefined>;
    /**
     * UUID of the<span pulumi-lang-nodejs=" authentik.RequestRule " pulumi-lang-dotnet=" authentik.RequestRule " pulumi-lang-go=" RequestRule " pulumi-lang-python=" RequestRule " pulumi-lang-yaml=" authentik.RequestRule " pulumi-lang-java=" authentik.RequestRule " pulumi-lang-hcl=" authentik_request_rule "> authentik.RequestRule </span>this binding applies.
     */
    rule: pulumi.Input<string>;
    /**
     * ID of the object this binding makes requestable.
     */
    target: pulumi.Input<string>;
}
