// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RequestRule extends pulumi.CustomResource {
    /**
     * Get an existing RequestRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RequestRuleState, opts?: pulumi.CustomResourceOptions): RequestRule {
        return new RequestRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/requestRule:RequestRule';

    /**
     * Returns true if the given object is an instance of RequestRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RequestRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RequestRule.__pulumiType;
    }

    /**
     * Generated.
     */
    declare public readonly minReviewers: pulumi.Output<number>;
    /**
     * Generated.
     */
    declare public readonly minReviewersIsPerGroup: pulumi.Output<boolean>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`direct`" pulumi-lang-dotnet="`Direct`" pulumi-lang-go="`direct`" pulumi-lang-python="`direct`" pulumi-lang-yaml="`direct`" pulumi-lang-java="`direct`" pulumi-lang-hcl="`direct`">`direct`</span>
     *   - <span pulumi-lang-nodejs="`randomMinReviewers`" pulumi-lang-dotnet="`RandomMinReviewers`" pulumi-lang-go="`randomMinReviewers`" pulumi-lang-python="`random_min_reviewers`" pulumi-lang-yaml="`randomMinReviewers`" pulumi-lang-java="`randomMinReviewers`" pulumi-lang-hcl="`random_min_reviewers`">`randomMinReviewers`</span>
     *      Generated.
     */
    declare public readonly notificationMode: pulumi.Output<string>;
    declare public readonly notificationTransports: pulumi.Output<string[] | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`any`" pulumi-lang-dotnet="`Any`" pulumi-lang-go="`any`" pulumi-lang-python="`any`" pulumi-lang-yaml="`any`" pulumi-lang-java="`any`" pulumi-lang-hcl="`any`">`any`</span>
     *      Generated.
     */
    declare public readonly policyEngineMode: pulumi.Output<string>;
    /**
     * UUID or slug of the flow shown to the requester when creating a request against this rule.
     */
    declare public readonly requestFlow: pulumi.Output<string | undefined>;
    declare public readonly requestRuleId: pulumi.Output<string>;
    /**
     * Objects currently bound to this rule, derived from its request rule bindings. Generated.
     */
    declare public /*out*/ readonly targets: pulumi.Output<string[]>;

    /**
     * Create a RequestRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: RequestRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RequestRuleArgs | RequestRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RequestRuleState | undefined;
            resourceInputs["minReviewers"] = state?.minReviewers;
            resourceInputs["minReviewersIsPerGroup"] = state?.minReviewersIsPerGroup;
            resourceInputs["name"] = state?.name;
            resourceInputs["notificationMode"] = state?.notificationMode;
            resourceInputs["notificationTransports"] = state?.notificationTransports;
            resourceInputs["policyEngineMode"] = state?.policyEngineMode;
            resourceInputs["requestFlow"] = state?.requestFlow;
            resourceInputs["requestRuleId"] = state?.requestRuleId;
            resourceInputs["targets"] = state?.targets;
        } else {
            const args = argsOrState as RequestRuleArgs | undefined;
            resourceInputs["minReviewers"] = args?.minReviewers;
            resourceInputs["minReviewersIsPerGroup"] = args?.minReviewersIsPerGroup;
            resourceInputs["name"] = args?.name;
            resourceInputs["notificationMode"] = args?.notificationMode;
            resourceInputs["notificationTransports"] = args?.notificationTransports;
            resourceInputs["policyEngineMode"] = args?.policyEngineMode;
            resourceInputs["requestFlow"] = args?.requestFlow;
            resourceInputs["requestRuleId"] = args?.requestRuleId;
            resourceInputs["targets"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RequestRule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RequestRule resources.
 */
export interface RequestRuleState {
    /**
     * Generated.
     */
    minReviewers?: pulumi.Input<number | undefined>;
    /**
     * Generated.
     */
    minReviewersIsPerGroup?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`direct`" pulumi-lang-dotnet="`Direct`" pulumi-lang-go="`direct`" pulumi-lang-python="`direct`" pulumi-lang-yaml="`direct`" pulumi-lang-java="`direct`" pulumi-lang-hcl="`direct`">`direct`</span>
     *   - <span pulumi-lang-nodejs="`randomMinReviewers`" pulumi-lang-dotnet="`RandomMinReviewers`" pulumi-lang-go="`randomMinReviewers`" pulumi-lang-python="`random_min_reviewers`" pulumi-lang-yaml="`randomMinReviewers`" pulumi-lang-java="`randomMinReviewers`" pulumi-lang-hcl="`random_min_reviewers`">`randomMinReviewers`</span>
     *      Generated.
     */
    notificationMode?: pulumi.Input<string | undefined>;
    notificationTransports?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`any`" pulumi-lang-dotnet="`Any`" pulumi-lang-go="`any`" pulumi-lang-python="`any`" pulumi-lang-yaml="`any`" pulumi-lang-java="`any`" pulumi-lang-hcl="`any`">`any`</span>
     *      Generated.
     */
    policyEngineMode?: pulumi.Input<string | undefined>;
    /**
     * UUID or slug of the flow shown to the requester when creating a request against this rule.
     */
    requestFlow?: pulumi.Input<string | undefined>;
    requestRuleId?: pulumi.Input<string | undefined>;
    /**
     * Objects currently bound to this rule, derived from its request rule bindings. Generated.
     */
    targets?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a RequestRule resource.
 */
export interface RequestRuleArgs {
    /**
     * Generated.
     */
    minReviewers?: pulumi.Input<number | undefined>;
    /**
     * Generated.
     */
    minReviewersIsPerGroup?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`direct`" pulumi-lang-dotnet="`Direct`" pulumi-lang-go="`direct`" pulumi-lang-python="`direct`" pulumi-lang-yaml="`direct`" pulumi-lang-java="`direct`" pulumi-lang-hcl="`direct`">`direct`</span>
     *   - <span pulumi-lang-nodejs="`randomMinReviewers`" pulumi-lang-dotnet="`RandomMinReviewers`" pulumi-lang-go="`randomMinReviewers`" pulumi-lang-python="`random_min_reviewers`" pulumi-lang-yaml="`randomMinReviewers`" pulumi-lang-java="`randomMinReviewers`" pulumi-lang-hcl="`random_min_reviewers`">`randomMinReviewers`</span>
     *      Generated.
     */
    notificationMode?: pulumi.Input<string | undefined>;
    notificationTransports?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>
     *   - <span pulumi-lang-nodejs="`any`" pulumi-lang-dotnet="`Any`" pulumi-lang-go="`any`" pulumi-lang-python="`any`" pulumi-lang-yaml="`any`" pulumi-lang-java="`any`" pulumi-lang-hcl="`any`">`any`</span>
     *      Generated.
     */
    policyEngineMode?: pulumi.Input<string | undefined>;
    /**
     * UUID or slug of the flow shown to the requester when creating a request against this rule.
     */
    requestFlow?: pulumi.Input<string | undefined>;
    requestRuleId?: pulumi.Input<string | undefined>;
}
