// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class UserOffboarding extends pulumi.CustomResource {
    /**
     * Get an existing UserOffboarding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserOffboardingState, opts?: pulumi.CustomResourceOptions): UserOffboarding {
        return new UserOffboarding(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/userOffboarding:UserOffboarding';

    /**
     * Returns true if the given object is an instance of UserOffboarding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserOffboarding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserOffboarding.__pulumiType;
    }

    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`deactivate`" pulumi-lang-dotnet="`Deactivate`" pulumi-lang-go="`deactivate`" pulumi-lang-python="`deactivate`" pulumi-lang-yaml="`deactivate`" pulumi-lang-java="`deactivate`" pulumi-lang-hcl="`deactivate`">`deactivate`</span>
     *   - <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`" pulumi-lang-hcl="`delete`">`delete`</span>
     *      Generated.
     */
    declare public readonly action: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public /*out*/ readonly executedAt: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public readonly revokeSessions: pulumi.Output<boolean>;
    /**
     * Generated.
     */
    declare public readonly revokeTokens: pulumi.Output<boolean>;
    /**
     * Absolute RFC3339 time at which the offboarding action is executed.
     */
    declare public readonly scheduledAt: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * PK of the user to offboard.
     */
    declare public readonly user: pulumi.Output<number>;
    declare public readonly userOffboardingId: pulumi.Output<string>;

    /**
     * Create a UserOffboarding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserOffboardingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserOffboardingArgs | UserOffboardingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserOffboardingState | undefined;
            resourceInputs["action"] = state?.action;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["executedAt"] = state?.executedAt;
            resourceInputs["revokeSessions"] = state?.revokeSessions;
            resourceInputs["revokeTokens"] = state?.revokeTokens;
            resourceInputs["scheduledAt"] = state?.scheduledAt;
            resourceInputs["status"] = state?.status;
            resourceInputs["user"] = state?.user;
            resourceInputs["userOffboardingId"] = state?.userOffboardingId;
        } else {
            const args = argsOrState as UserOffboardingArgs | undefined;
            if (args?.scheduledAt === undefined && !opts.urn) {
                throw new Error("Missing required property 'scheduledAt'");
            }
            if (args?.user === undefined && !opts.urn) {
                throw new Error("Missing required property 'user'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["revokeSessions"] = args?.revokeSessions;
            resourceInputs["revokeTokens"] = args?.revokeTokens;
            resourceInputs["scheduledAt"] = args?.scheduledAt;
            resourceInputs["user"] = args?.user;
            resourceInputs["userOffboardingId"] = args?.userOffboardingId;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["executedAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UserOffboarding.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering UserOffboarding resources.
 */
export interface UserOffboardingState {
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`deactivate`" pulumi-lang-dotnet="`Deactivate`" pulumi-lang-go="`deactivate`" pulumi-lang-python="`deactivate`" pulumi-lang-yaml="`deactivate`" pulumi-lang-java="`deactivate`" pulumi-lang-hcl="`deactivate`">`deactivate`</span>
     *   - <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`" pulumi-lang-hcl="`delete`">`delete`</span>
     *      Generated.
     */
    action?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    executedAt?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    revokeSessions?: pulumi.Input<boolean | undefined>;
    /**
     * Generated.
     */
    revokeTokens?: pulumi.Input<boolean | undefined>;
    /**
     * Absolute RFC3339 time at which the offboarding action is executed.
     */
    scheduledAt?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * PK of the user to offboard.
     */
    user?: pulumi.Input<number | undefined>;
    userOffboardingId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a UserOffboarding resource.
 */
export interface UserOffboardingArgs {
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`deactivate`" pulumi-lang-dotnet="`Deactivate`" pulumi-lang-go="`deactivate`" pulumi-lang-python="`deactivate`" pulumi-lang-yaml="`deactivate`" pulumi-lang-java="`deactivate`" pulumi-lang-hcl="`deactivate`">`deactivate`</span>
     *   - <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`" pulumi-lang-hcl="`delete`">`delete`</span>
     *      Generated.
     */
    action?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    revokeSessions?: pulumi.Input<boolean | undefined>;
    /**
     * Generated.
     */
    revokeTokens?: pulumi.Input<boolean | undefined>;
    /**
     * Absolute RFC3339 time at which the offboarding action is executed.
     */
    scheduledAt: pulumi.Input<string>;
    /**
     * PK of the user to offboard.
     */
    user: pulumi.Input<number>;
    userOffboardingId?: pulumi.Input<string | undefined>;
}
