import * as fs from 'node:fs';
import * as path from 'node:path';
import * as pulumi from '@pulumi/pulumi';
import {
  applicationSlug,
  authentikBaseUrl,
  authentikBootstrapPassword,
  authentikPgPass,
  authentikSecretKey,
  grafanaAdminPassword,
  grafanaAdminUser,
  pgPassword,
} from './config';

// __dirname = infrastructure/src; two levels up reaches the repo root
const dotEnvPath = path.resolve(__dirname, '../../.env');

interface DotEnvInputs {
  envPath: string;
  content: string;
}

const dotEnvImpl: pulumi.dynamic.ResourceProvider = {
  async create(inputs: DotEnvInputs) {
    fs.writeFileSync(inputs.envPath, inputs.content, 'utf8');
    return { id: inputs.envPath, outs: inputs };
  },
  async update(_id: string, _olds: DotEnvInputs, news: DotEnvInputs) {
    fs.writeFileSync(news.envPath, news.content, 'utf8');
    return { outs: news };
  },
  async diff(_id: string, olds: DotEnvInputs, news: DotEnvInputs) {
    return { changes: olds.content !== news.content || olds.envPath !== news.envPath };
  },
  async delete() {
    // Leave .env in place; docker compose may need it after destroy
  },
};

class DotEnvResource extends pulumi.dynamic.Resource {
  constructor(
    name: string,
    args: { envPath: pulumi.Input<string>; content: pulumi.Input<string> },
    opts?: pulumi.CustomResourceOptions,
  ) {
    super(dotEnvImpl, name, args, opts);
  }
}

export function createDotEnv(): DotEnvResource {
  // Internal Docker network URL (container-to-container)
  const authentikInternalBase = 'http://authentik-server:9000';
  const oidcPath = `/application/o/${applicationSlug}`;

  const content = pulumi
    .all([
      authentikSecretKey,
      authentikPgPass,
      authentikBootstrapPassword,
      grafanaAdminUser,
      grafanaAdminPassword,
      pgPassword,
    ])
    .apply(([secretKey, pgPass, bootstrapPw, grafanaUser, grafanaPw, wendigoPg]) =>
      [
        '# Generated by pulumi up — do not edit manually',
        '',
        '# Authentik server',
        `AUTHENTIK_SECRET_KEY=${secretKey}`,
        `AUTHENTIK_PG_PASS=${pgPass}`,
        'AUTHENTIK_PG_USER=authentik',
        'AUTHENTIK_PG_DB=authentik',
        'AUTHENTIK_BOOTSTRAP_EMAIL=admin@wendigo.dev',
        `AUTHENTIK_BOOTSTRAP_PASSWORD=${bootstrapPw}`,
        '',
        '# Grafana',
        `GRAFANA_ADMIN_USER=${grafanaUser}`,
        `GRAFANA_ADMIN_PASSWORD=${grafanaPw}`,
        '',
        '# Game database',
        `WENDIGO_PG_PASSWORD=${wendigoPg}`,
        '',
        '# Backend OIDC (internal Docker network)',
        `OIDC_ISSUER_URL=${authentikInternalBase}${oidcPath}/`,
        `OIDC_EXPECTED_ISSUER=${authentikBaseUrl}${oidcPath}/`,
        `AUTHENTIK_JWKS_URL=${authentikInternalBase}${oidcPath}/jwks/`,
        '',
        '# Frontend build args',
        `VITE_AUTHENTIK_URL=${authentikBaseUrl}${oidcPath}`,
        `VITE_AUTHENTIK_CLIENT_ID=wendigo-dev`,
      ].join('\n'),
    );

  return new DotEnvResource('dotenv', { envPath: dotEnvPath, content });
}
