encryptionsalt: v1:FNCdHH+8ZCo=:v1:HW42hgYYAhjRbkKW:TTX4G+aRDKDApPysVdWSl7MjVMTzig==
config:
  wendigo:googleClientId: 276321618988-c9gn61hqql7fspuva25g9lam4jh25mvg.apps.googleusercontent.com
  wendigo:googleClientSecret:
    secure: v1:azTibjLElFzpsQIU:sV6EWGUdFTq0985Kgnqqc8Ad9wUU0eneLG9WfRt91H2xkkaFKYQvSnmwA89NoJ2ebqYh
  wendigo:authentikSecretKey:
    secure: v1:ez3Q1qKY90qNah2x:2rcfcZXHABCdNOibuxH2Flt4WacTfOrmJms3SjCEl+IHqkhYTbynvpenX6DkIfLsl6fNsaRVIr3YdecZleuf4W+Zr1Vh0K4erA==
  wendigo:authentikPgPass:
    secure: v1:9UzizHuhBuMzMges:dSZpJnepKxJoOy9QVaRFocSTOj55QpHnPQ==
  wendigo:authentikBootstrapPassword:
    secure: v1:EN7FsABhZbkvD6WT:2z6SEHoXB5tSO7UZNfgRhN5SsS+5k2IC5XvsRZHmUxVWS9GeMyAItoKH8UqsYouQTA==
  wendigo:pgPassword:
    secure: v1:PfppNrXTfNHUv2rz:9oJKH0ZU4a12hxca3ViXxU0rZNhoberZ
  wendigo:oidcIncludePropertyMappings: "true"
  grafana:adminPassword:
    secure: v1:nd9X4UmfyCGT88nQ:55KD27UTGtJDVqUp3w71wSBi5TDF
  authentik:token:
    secure: v1:qGdf/KJngnQOh0Pk:TBv889MnWA43zRWoN0yfSe+kPvy75HVHhQWdatuKdBwBUSkeONBUIZV0dGnX5w9FMy34Tj2FMzFzDow01cUlqchLG+bhvPrs+Lfc+g==
