name: CI

on:
  push:
    branches: [main, night]
  pull_request:
    branches: [main, night]

jobs:
  backend:
    name: Lint & Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      CGO_ENABLED: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true

      - name: Run golangci-lint (Force build from source)
        run: |
          # On compile le linter directement avec Go 1.25
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
          # On l'exécute
          $(go env GOPATH)/bin/golangci-lint run ./...

      - name: Build backend
        run: go build -v -o ./server-bin ./cmd/server

      - name: Run unit tests
        run: go test -v -race -cover ./...